config:
  data:
    otel_traces_export:
      endpoint: http://opentelemetry-collector.opentelemetry-system.svc.cluster.local:4317
    otel_metrics_export:
      endpoint: http://opentelemetry-collector.opentelemetry-system.svc.cluster.local:4317

preset: application
