environments:
  k3d:
    values:
      - env/k3d/version.yaml
  production:
    values:
      - env/production/version.yaml

---

repositories:
  - name: cilium
    url: https://helm.cilium.io/

releases:
  - name: cilium
    namespace: kube-system
    chart: cilium/cilium
    version: "{{ .Values.version }}"
    values:
      - values/{{ .Environment.Name }}.yaml
