environments:
  k3d:
    values:
      - env/k3d/version.yaml
  production:
    values:
      - env/production/version.yaml

---
repositories:
  - name: fluent
    url: https://fluent.github.io/helm-charts

releases:
  - name: fluent-bit
    namespace: monitoring
    chart: fluent/fluent-bit
    version: "{{ .Values.version }}"
    values:
      - values/{{ .Environment.Name }}.yaml
