environments:
  k3d:
---
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: tempo
    namespace: monitoring
    chart: grafana/tempo
    version: "1.8.0"
    values:
      - values.yaml
    strategicMergePatches:
      - apiVersion: monitoring.coreos.com/v1
        kind: ServiceMonitor
        metadata:
          name: tempo
          namespace: monitoring
