environments:
  k3d:
---
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: tempo
    namespace: monitoring
    chart: grafana/tempo
    version: "1.23.1"
    values:
      - values.yaml
