# =============================================================================
# k3d Cluster Kustomization
# =============================================================================
# This kustomization includes all resources for the k3d cluster:
#   - Git repositories for FluxCD
#   - Hydrated manifests
# =============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - repositories
  - ../../manifests/k3d
