environments:
  k3d:
---
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: loki
    namespace: monitoring
    chart: grafana/loki
    version: "6.49.0"
    values:
      - values.yaml
