---
apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry-operator-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
