---
# Source: beyla/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: beyla
  namespace: monitoring
  labels:
    helm.sh/chart: beyla-1.6.0
    app.kubernetes.io/name: beyla
    app.kubernetes.io/instance: beyla
    app.kubernetes.io/version: "1.9.6"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: beyla
    app.kubernetes.io/component: rbac
automountServiceAccountToken: true
---
# Source: beyla/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: beyla
  namespace: monitoring
  labels:
    helm.sh/chart: beyla-1.6.0
    app.kubernetes.io/name: beyla
    app.kubernetes.io/instance: beyla
    app.kubernetes.io/version: "1.9.6"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: beyla
    app.kubernetes.io/component: config
data:
  beyla-config.yml: |
    attributes:
      kubernetes:
        enable: true
      select:
        beyla_network_flow_bytes:
          include:
          - k8s.src.owner.type
          - k8s.dst.owner.type
          - direction
    discovery:
      services:
      - k8s_namespace: default
    filter:
      network:
        k8s_dst_owner_name:
          not_match: '{kube*,*jaeger-agent*,*prometheus*,*promtail*,*grafana-agent*}'
        k8s_src_owner_name:
          not_match: '{kube*,*jaeger-agent*,*prometheus*,*promtail*,*grafana-agent*}'
    otel_metrics_export:
      endpoint: http://opentelemetry-collector.opentelemetry-system.svc.cluster.local:4317
      interval: 30s
    otel_traces_export:
      endpoint: http://opentelemetry-collector.opentelemetry-system.svc.cluster.local:4317
      interval: 5s
      max_export_batch_size: 512
    prometheus_export:
      path: /metrics
      port: 9090
    routes:
      unmatched: heuristic
---
# Source: beyla/templates/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: beyla
  labels:
    helm.sh/chart: beyla-1.6.0
    app.kubernetes.io/name: beyla
    app.kubernetes.io/instance: beyla
    app.kubernetes.io/version: "1.9.6"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: beyla
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: [ "apps" ]
    resources: [ "replicasets" ]
    verbs: [ "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "pods", "services", "nodes" ]
    verbs: [ "list", "watch", "get" ]
---
# Source: beyla/templates/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: beyla
  labels:
    helm.sh/chart: beyla-1.6.0
    app.kubernetes.io/name: beyla
    app.kubernetes.io/instance: beyla
    app.kubernetes.io/version: "1.9.6"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: beyla
    app.kubernetes.io/component: rbac
subjects:
  - kind: ServiceAccount
    name: beyla
    namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: beyla
---
# Source: beyla/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: beyla
  namespace: monitoring
  labels:
    helm.sh/chart: beyla-1.6.0
    app.kubernetes.io/name: beyla
    app.kubernetes.io/instance: beyla
    app.kubernetes.io/version: "1.9.6"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: beyla
    app.kubernetes.io/component: networking
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    app.kubernetes.io/name: beyla
    app.kubernetes.io/instance: beyla
---
# Source: beyla/templates/daemon-set.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beyla
  namespace: monitoring
  labels:
    helm.sh/chart: beyla-1.6.0
    app.kubernetes.io/name: beyla
    app.kubernetes.io/instance: beyla
    app.kubernetes.io/version: "1.9.6"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: beyla
    app.kubernetes.io/component: workload
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: beyla
      app.kubernetes.io/instance: beyla
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: f767227e969ae5c9b88df130b01b06f42b229540fa86c802297d461199107e7a
      labels:
        helm.sh/chart: beyla-1.6.0
        app.kubernetes.io/name: beyla
        app.kubernetes.io/instance: beyla
        app.kubernetes.io/version: "1.9.6"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: beyla
        app.kubernetes.io/component: workload
    spec:
      serviceAccountName: beyla
      hostPID: true
      containers:
        - name: beyla
          image: docker.io/grafana/beyla:1.9.6
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          ports:
          - name: metrics
            containerPort: 9090
            protocol: TCP
          env:
            - name: BEYLA_CONFIG_PATH
              value: "/etc/beyla/config/beyla-config.yml"
          volumeMounts:
            - mountPath: /etc/beyla/config
              name: beyla-config
      volumes:
        - name: beyla-config
          configMap:
            name: beyla
---
# Source: beyla/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: beyla
  namespace: monitoring
  labels:
    helm.sh/chart: beyla-1.6.0
    app.kubernetes.io/name: beyla
    app.kubernetes.io/instance: beyla
    app.kubernetes.io/version: "1.9.6"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: beyla
    app.kubernetes.io/component: metrics
spec:
  endpoints:
    - port: metrics
      path: /metrics
      scheme: http
  jobLabel: beyla
  selector:
    matchLabels:
      helm.sh/chart: beyla-1.6.0
      app.kubernetes.io/name: beyla
      app.kubernetes.io/instance: beyla
      app.kubernetes.io/version: "1.9.6"
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: beyla

