---
# Source: beyla/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: beyla
  namespace: monitoring
  labels:
    helm.sh/chart: beyla-1.10.4
    app.kubernetes.io/name: beyla
    app.kubernetes.io/instance: beyla
    app.kubernetes.io/version: "2.8.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: beyla
    app.kubernetes.io/component: rbac
automountServiceAccountToken: true
---
# Source: beyla/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: beyla
  namespace: monitoring
  labels:
    helm.sh/chart: beyla-1.10.4
    app.kubernetes.io/name: beyla
    app.kubernetes.io/instance: beyla
    app.kubernetes.io/version: "2.8.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: beyla
    app.kubernetes.io/component: config
data:
  beyla-config.yml: |
    attributes:
      kubernetes:
        enable: true
    discovery:
      services:
      - k8s_namespace: default
        open_ports: 80,443,8080,3000
      - k8s_namespace: monitoring
        open_ports: 80,443,8080,3000,3100,9090
      - k8s_namespace: flux-system
        open_ports: 80,443,8080,9292
    filter:
      network:
        k8s_dst_owner_name:
          not_match: '{kube*,*prometheus*,*grafana-agent*}'
        k8s_src_owner_name:
          not_match: '{kube*,*prometheus*,*grafana-agent*}'
    otel_metrics_export:
      endpoint: http://opentelemetry-collector.opentelemetry-system.svc.cluster.local:4317
      interval: 30s
      protocol: grpc
    otel_traces_export:
      endpoint: http://opentelemetry-collector.opentelemetry-system.svc.cluster.local:4317
      interval: 5s
      max_export_batch_size: 512
      protocol: grpc
    prometheus_export:
      path: /metrics
      port: 9090
    routes:
      unmatched: heuristic
---
# Source: beyla/templates/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: beyla
  labels:
    helm.sh/chart: beyla-1.10.4
    app.kubernetes.io/name: beyla
    app.kubernetes.io/instance: beyla
    app.kubernetes.io/version: "2.8.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: beyla
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: [ "apps" ]
    resources: [ "replicasets" ]
    verbs: [ "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "pods", "services", "nodes" ]
    verbs: [ "list", "watch", "get" ]
---
# Source: beyla/templates/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: beyla
  labels:
    helm.sh/chart: beyla-1.10.4
    app.kubernetes.io/name: beyla
    app.kubernetes.io/instance: beyla
    app.kubernetes.io/version: "2.8.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: beyla
    app.kubernetes.io/component: rbac
subjects:
  - kind: ServiceAccount
    name: beyla
    namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: beyla
---
# Source: beyla/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: beyla
  namespace: monitoring
  labels:
    helm.sh/chart: beyla-1.10.4
    app.kubernetes.io/name: beyla
    app.kubernetes.io/instance: beyla
    app.kubernetes.io/version: "2.8.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: beyla
    app.kubernetes.io/component: networking
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    app.kubernetes.io/name: beyla
    app.kubernetes.io/instance: beyla
---
# Source: beyla/templates/daemon-set.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beyla
  namespace: monitoring
  labels:
    helm.sh/chart: beyla-1.10.4
    app.kubernetes.io/name: beyla
    app.kubernetes.io/instance: beyla
    app.kubernetes.io/version: "2.8.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: beyla
    app.kubernetes.io/component: workload
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: beyla
      app.kubernetes.io/instance: beyla
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: a2e3960b2dc627d0e1b0a48553f952c6f8f31197e27c2fdf0853abe6e71dc52b
      labels:
        helm.sh/chart: beyla-1.10.4
        app.kubernetes.io/name: beyla
        app.kubernetes.io/instance: beyla
        app.kubernetes.io/version: "2.8.4"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: beyla
        app.kubernetes.io/component: workload
    spec:
      serviceAccountName: beyla
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: beyla
          image: docker.io/grafana/beyla:2.8.4
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          ports:
          - name: metrics
            containerPort: 9090
            protocol: TCP
          env:
            - name: BEYLA_CONFIG_PATH
              value: "/etc/beyla/config/beyla-config.yml"
          volumeMounts:
            - mountPath: /etc/beyla/config
              name: beyla-config
            - mountPath: /sys/fs/cgroup
              name: cgroup
      volumes:
        - name: beyla-config
          configMap:
            name: beyla
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
---
# Source: beyla/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: beyla
  namespace: monitoring
  labels:
    helm.sh/chart: beyla-1.10.4
    app.kubernetes.io/name: beyla
    app.kubernetes.io/instance: beyla
    app.kubernetes.io/version: "2.8.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: beyla
    app.kubernetes.io/component: metrics
spec:
  endpoints:
    - port: metrics
      path: /metrics
      scheme: http
  jobLabel: beyla
  selector:
    matchLabels:
      helm.sh/chart: beyla-1.10.4
      app.kubernetes.io/name: beyla
      app.kubernetes.io/instance: beyla
      app.kubernetes.io/version: "2.8.4"
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: beyla

