resources:
- beyla.yaml
- cilium.yaml
- coredns.yaml
- dashboard.yaml
- fluent-bit.yaml
- gateway-api.yaml
- loki.yaml
- opentelemetry.yaml
- opentelemetry-collector.yaml
- prometheus-operator.yaml
- tempo.yaml
- 00-namespaces.yaml
