apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - gatewayclass.yaml
  - hubble-httproute.yaml
  - referencegrant.yaml
  - servicemonitor.yaml
  - service.yaml
