environments:
  k3d:
    values:
      - env/k3d/version.yaml
  production:
    values:
      - env/production/version.yaml

---
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: tempo
    namespace: monitoring
    chart: grafana/tempo
    version: "{{ .Values.version }}"
    values:
      - values/{{ .Environment.Name }}.yaml
