# =============================================================================
# Kube-Prometheus-Stack Helmfile for k3d
# =============================================================================
# This chart installs:
#   - Prometheus Operator
#   - Prometheus
#   - Alertmanager
#   - Grafana
#   - Various exporters and ServiceMonitors
# =============================================================================
environments:
  k3d:
---
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: "61.9.0"
    values:
      - values.yaml
