environments:
  k3d:
---
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: beyla
    namespace: monitoring
    chart: grafana/beyla
    version: "1.10.4"
    values:
      - values.yaml
