name: 'CI Gatekeeper'

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'

jobs:
  ci-gatekeeper:
    name: CI Gatekeeper
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Wait for other workflows
        uses: int128/wait-for-workflows-action@v1
        with:
          max-timeout-seconds: 1800 # 30 minutes
